starpool/blogapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from blogapp import views

app_name = "blog"

urlpatterns = [
    path('', views.home, name='home'),
    path('detail/<int:id>/', views.detail, name='detail'),
    path('comment/<int:id>/', views.commentBox, name='commentBox'),
    path('detail/<int:id>/<int:comment_id>/', views.comment_detail, name='comment_detail'),

    # 이제 별점주는 채팅 어케 보내지...?
    path('commentReview/<int:id>/<int:comment_id>/', views.comment_review, name='comment_review'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

starpool/starpool/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from blogapp import views
from django.conf import settings
from django.conf.urls.static import static
from blogapp.views import initial


urlpatterns = [
    path('admin/', admin.site.urls),
    path('main/', include('blogapp.urls', namespace='blog')),
    path('accounts/',include('userapp.urls')),
    path('',initial, name="initial")

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

starpool/userapp/urls.py
from django.contrib import admin
from django.urls import path
from .views import *

urlpatterns = [
    path('signup/',signup, name='signup'),
    path('login/',login, name='login'),
    path('logout/',logout,name='logout'),
    path('myinfo/<int:user_id>/',myinfo,name='myinfo'),
    path('update/<int:user_id>/',update,name='update'),
    path('changepwd/<int:user_id>/',change_password,name='change_password'),
]

starpool/userapp/models.py
from django.db import models
from django.contrib.auth.models import (BaseUserManager, AbstractBaseUser)

class UserManager(BaseUserManager):
    def create_user(self, email,name, password=None):
        if not email:
            raise ValueError('이메일을 작성해주세요.')
        
        if not name:
            raise ValueError('이름을 작성해주세요.')

        user=self.model(
            name=name,
            email=self.normalize_email(email)
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, name, email, password):
        # create_user의 인자와 동일해야함
        user=self.create_user(
            email,
            name=name,
            password=password
        )
        user.is_admin=True
        user.save(using=self._db)
        return user


choice=(
    (0,'False'),
    (1,'True')
)

class User(AbstractBaseUser):
    name=models.CharField(max_length=30)
    email=models.EmailField(
        verbose_name='email',
        max_length=255,
        unique=True,
    )
    profile_img=models.ImageField(upload_to = "pf_img/", null=True, blank=True)
    portfolio=models.FileField(upload_to = "pofol/", null=True, blank=True)
    school=models.CharField(max_length=30, blank=True, default='')
    bio=models.CharField(max_length=500, blank=True, default='')
    star=models.BooleanField(default = True)
    review=models.BooleanField(default = True)
    is_active=models.BooleanField(default=True)
    is_admin=models.BooleanField(default=False)

    objects=UserManager()

    USERNAME_FIELD='email'
    REQUIRED_FIELDS=['name']

    def __str__(self):
        return self.email
    def has_perm(self, perm, obj=None):
        return True

    def has_module_perms(self, app_label):
        return True
    
    @property
    def is_staff(self):
        return self.is_admin

starpool/userapp/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import ReadOnlyPasswordHashField

from .models import User


class UserCreationForm(forms.ModelForm):
    pwd1=forms.CharField(label='Password',widget=forms.PasswordInput)
    pwd2=forms.CharField(label='Password confirm',widget=forms.PasswordInput)

    class Meta:
        model=User
        fields=('name','email')
    
    def clean_pwd2(self):
        pwd1=self.cleaned_data.get("pwd1")
        pwd2=self.cleaned_data.get("pwd2")
        if pwd1 and pwd2 and pwd1!=pwd2:
            raise forms.ValidationError("비밀번호가 일치하지 않습니다.")
        return pwd2
    
    def save(self, commit=True):
        user=super().save(commit=False)
        user.set_password(self.cleaned_data["pwd1"])
        if commit:
            user.save()
        return user

class UserChangeForm(forms.ModelForm):
    # 관리자 권한
    password=ReadOnlyPasswordHashField()

    class Meta:
        model=User
        fields=('name','email','password', 'profile_img','portfolio','school','bio','star','review')
    
    # def clean_password(self):
    #     return self.initial["password"]


class CustomUserChangeForm(UserChangeForm):
    # 일반 사용자 권한
    class Meta:
        model=get_user_model() # 현재 활성화된 사용자 모델을 반환
        fields=('name', 'profile_img','portfolio','school','bio','star','review')

starpool/userapp/views.py
from django.shortcuts import render
from django.contrib import auth
from django.contrib.auth import authenticate
from .models import User
from django.shortcuts import render, redirect, get_object_or_404
from .forms import CustomUserChangeForm
from django.contrib.auth.hashers import check_password
from django.contrib import messages,auth
from django.contrib.auth import get_user_model
from blogapp.models import *

def signup(request):
    if request.method=='POST':
        if request.POST['password1']==request.POST['password2']:
            user=User.objects.create_user(
                email=request.POST['email'],
                name=request.POST['name'],
                password=request.POST['password1']
            )
            auth.login(request, user)
            return redirect('login')
        
    return render(request, 'signup.html')


def login(request):
    if request.method=='POST':
        email=request.POST['email']
        password=request.POST['password']
        user=authenticate(request,email=email, password=password)

        if user is not None:
            auth.login(request,user)
            return redirect('blog:home')
        else:
            # 로그인 실패 시
            return render(request, 'login.html',{'error':'user info is not correct'})
    
    else:
        # GET 메소드일 시
        return render(request, 'login.html')


def logout(request):
    auth.logout(request)
    return redirect('blog:home')


def myinfo(request, user_id):
    login_user=get_user_model()
    user=get_object_or_404(login_user, pk=user_id)
    com_box=CommentBox.objects.filter(writer=user).order_by('id')

    context={
        'user':user,
        'com_box':com_box
    }
    return render(request,'myinfo.html',context)


def update(request, user_id):
    if request.method=='POST':
        # request.FILES는 이미지 업로드 할 때 사용
        form=CustomUserChangeForm(request.POST, request.FILES, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('myinfo',user_id)
    else:
        form=CustomUserChangeForm(instance=request.user)
    
    context={
        'form':form,
    }
    return render(request, 'update.html',context)

def change_password(request, user_id):
    if request.method=='POST':
        user=request.user
        origin_password=request.POST['origin_password']
        if check_password(origin_password,user.password):
            password1=request.POST["password1"]
            password2=request.POST["password2"]

            if password1==password2:
                user.set_password(password1)
                user.save()
                auth.login(request,user)
                return redirect('myinfo',user_id)
            else:
                messages.error(request,'비밀번호가 일치하지 않습니다.')
        
        else:
            messages.error(request,'비밀번호가 맞지 않습니다.')
    
    return render(request,'change_password.html')

starpool/userapp/templates/change_password.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Star Pool</title>
    <link rel="stylesheet" href="{% static 'css/password.css' %}" />
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@300;400;500;700;900&display=swap"
      rel="stylesheet"
    />
  </head>
  <body>
  <nav>
            <div class="nav-item">
                <a href="{%url 'initial' %}"><img id="logo-img" src="{% static 'img/logo.png' %}" alt="navbar 로고"></img></a>
            </div>
            <div class="nav-item">
                <a href="{%url 'blog:home'%}">
                    <div id="mainpage">MainPage</div>
                </a>
                <!-- 여기 mypage, login, logout url 바꿔주세요!-->
                {% if user.is_authenticated %}
                <a href="{%url 'myinfo' user.pk %}">
                    <div id="mypage">MyPage</div>
                </a>
                {% else %}
                <a href="{%url 'login' %}">
                    <div id="mypage">MyPage</div>
                </a>
                {% endif %}
            </div>
            <div class="nav-item">
                {% if user.is_authenticated %}
                <a href="{%url 'logout'%}">
                    <div id="logout">Log Out</div>
                </a>
                {% else %}
                <a href="{%url 'login'%}">
                    <div id="login">Log In</div>
                </a>
                {% endif %}
            </div>
        </nav>

    <div class="content">
      <div class="password-title">비밀번호 변경</div>
      <div class="container">
        <form method="POST" action="{% url 'change_password' user.pk %}" class="form">
          <div>
            {% csrf_token %}
            <p>현재 비밀번호</p>
            <input
              class="password-input"
              name="origin_password"
              type="password"
            />
          </div>
          <div>
            <p>변경할 비밀번호</p>
            <input class="password-input" name="password1" type="password" />
          </div>
          <div>
            <p>비밀번호 확인</p>
            <input class="password-input" name="password2" type="password" />
          </div>
          <input class="btn btn-primary" type="submit" value="변경" />
        </form>
      </div>
    </div>

    <footer>
      <p class="footer">
        &copy; 2023 HERETHON 오디. STAR POOL ALL RIGHTS RESERVED.
      </p>
    </footer>
  </body>
</html>

starpool/userapp/templates/login.html
<!-- 프론트 html 적용 완료 -->
<!-- js 미적용 -->
{% load static %}
<!DOCTYPE html>
<html lang="ko">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Star Pool</title>
        <link rel="stylesheet" href="{% static 'css/login.css' %}" />
    </head>
    <body>
        {% block content %}
        <div class="content">
            <div id="logo">
                <a href="./splash.html"
                    ><img src="{% static 'img/logo_2.png' %}" alt="로그인 - 로고"
                /></a>
                <h6>STAR POOL과 함께 다양한 경험을 시작하세요</h6>
            </div>
            <div id="inputs">
                <form
                    method="post"
                    id="login-form"
                >
                {% csrf_token %}
                    <p>이메일</p>
                    <input
                        type="email"
                        id="email"
                        name="email"
                        placeholder="예&#41; likelion@gmail.com"
                    />

                    <p>비밀번호</p>
                    <input type="password" id="password" name="password"/>

                    <br />

                    <input type="submit" value="로그인" />
                </form>
            </div>
            {% endblock %}

            <div id="togo-signup">
                <p>계정이 없으십니까?&nbsp;</p>
                <a href="{% url 'signup' %}">회원가입하기</a>
            </div>
        </div>

        <footer>
            <p class="footer">
                &copy; 2023 HERETHON 오디. STAR POOL ALL RIGHTS RESERVED.
            </p>
        </footer>

    </body>
</html>

starpool/userapp/templates/myinfo.html
<!-- 프론트 html 적용 완료 -->
{% load static %}
{% if user.is_authenticated %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>userpage</title>
        <link rel="stylesheet" href="{% static 'css/userpage.css' %}" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
            href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@300;400;500;700;900&display=swap"
            rel="stylesheet"
        />
    </head>

    <body>
    <nav>
            <div class="nav-item">
                <a href="{%url 'initial' %}"><img id="logo-img" src="{% static 'img/logo.png' %}" alt="navbar 로고"></img></a>
            </div>
            <div class="nav-item">
                <a href="{%url 'blog:home'%}">
                    <div id="mainpage">MainPage</div>
                </a>
                <!-- 여기 mypage, login, logout url 바꿔주세요!-->
                {% if user.is_authenticated %}
                <a href="{%url 'myinfo' user.pk %}">
                    <div id="mypage">MyPage</div>
                </a>
                {% else %}
                <a href="{%url 'login' %}">
                    <div id="mypage">MyPage</div>
                </a>
                {% endif %}
            </div>
            <div class="nav-item">
                {% if user.is_authenticated %}
                <a href="{%url 'logout'%}">
                    <div id="logout">Log Out</div>
                </a>
                {% else %}
                <a href="{%url 'login'%}">
                    <div id="login">Log In</div>
                </a>
                {% endif %}
            </div>
        </nav>

        <wrapper>
            <!-- 사용자 정보 및 소개 -->
            <div class="user-info-container">
            <div id="user-info-left">
                <div class="user-profile-img"><img src="/media/{{ user.profile_img }}" class="img-img"
                ></div>
                <div class="user-name">{{ user.name }}</div>
                <div class="user-grade">
                <span>평균 평점</span>
                <span>3.5</span>
                </div>
                <!-- 포트폴리오 열람 -->
                {% if user.portfolio %}
                    <a href="{{ user.portfolio.url }}" class="portfolio-button" download>포트폴리오 보기</a>
                {% else %}
                    <button class="portfolio-button">포트폴리오 없음</button>
                {% endif %}
            </div>
            <div id="user-info-right">
                <div class="user-info-title">사용자 소개</div>
                <div class="user-info-content">{{ user.bio }}</div>
                <!-- 수정하기 버튼 -->
                <button class="edit-button" onclick="location.href='{% url 'update' user.pk %}'">
                수정하기
                </button>
            </div>
            </div>

            <!-- 해당 사용자가 작성한 게시글 모아보기 -->
            {% for cb in com_box %}
            <div class="post-container">
            <div id="post">
                <div id="userinfo">
                <img src="/media/{{ cb.writer.profile_img }}" alt="프로필" class="profile-img" />
                <div>
                    <span>{{ cb.writer }}</span>
                    <div class="posttime">{{ cb.date }}</div>
                </div>
                <div>
                    <!-- 공모전 이름 -->
                    <div class="contenst-text">{{ cb.post.title }}</div>
                    <div>
                    <div class="grade-text">평균 평점</div>
                    <div class="grade">3.5</div>
                    </div>
                </div>
                </div>
                <hr />
                <!-- 게시글 내용 -->
                <div class="content">{{ cb.content }}</div>
                <button><a href="{% url 'blog:comment_detail' cb.post.id cb.id %}">평가보기</a></button>
                <hr />
            </div>
            </div>
            {% endfor %}
        </wrapper>

        <footer>
        <p class="footer">&copy; 2023 HERETHON 오디. STAR POOL ALL RIGHTS RESERVED.
        </p>
    </footer>
    </body>
</html>
{% endif %}

starpool/userapp/templates/signup.html
<!-- 프론트 html 적용 완료 -->
<!-- js 미적용 -->
{% load static %}
<!DOCTYPE html>
<html lang="ko">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Star Pool</title>
        <link rel="stylesheet" href="{% static 'css/signup.css' %}" />
    </head>
    <body>
        {% block content %}
        <div class="content">
            <div id="logo">
                <a href="./splash.html"
                    ><img src="{% static 'img/logo_2.png' %}" alt="회원가입 - 로고"
                /></a>
                <h6>STAR POOL과 함께 다양한 경험을 시작하세요</h6>
            </div>
            <div id="inputs">
                <form
                    method="POST"
                    id="signup-form"
                >
                {% csrf_token %}
                    <p>이름</p>
                    <input
                        type="text"
                        id="name"
                        name="name"
                        placeholder="이름을 입력해주세요"
                    />
                    <p>이메일</p>
                    <input
                        type="text"
                        id="email"
                        name="email"
                        placeholder="예&#41; likelion@gmail.com"
                    />

                    <p>비밀번호</p>
                    <input
                        type="password"
                        id="password"
                        name="password1"
                        placeholder="영문/숫자/특수문자를 조합 (10자 이상)"
                    />
                    <p>비밀번호 확인</p>
                    <input
                        type="password"
                        id="password2"
                        name="password2"
                        placeholder="비밀번호를 다시 한 번 입력해주세요"
                    />

                    <input type="submit" value="가입하기"/>
                </form>
            </div>
            {% endblock %}

            <div id="togo-login">
                <p>이미 계정이 있으십니까?&nbsp;</p>
                <a href="{% url 'login' %}">로그인하기</a>
            </div>
        </div>
        <footer>
            <p class="footer">
                &copy; 2023 HERETHON 오디. STAR POOL ALL RIGHTS RESERVED.
            </p>
        </footer>

    </body>
</html>

starpool/userapp/templates/update.html
<!-- 프론트 html 적용 완료 -->
{% load static %}
<!DOCTYPE html>
<head> 
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <title></title>
    <link rel="stylesheet" href="{% static 'css/mypage.css' %}" />
</head>
<body>
<nav>
            <div class="nav-item">
                <a href="{%url 'initial' %}"><img id="logo-img" src="{% static 'img/logo.png' %}" alt="navbar 로고"></img></a>
            </div>
            <div class="nav-item">
                <a href="{%url 'blog:home'%}">
                    <div id="mainpage">MainPage</div>
                </a>
                <!-- 여기 mypage, login, logout url 바꿔주세요!-->
                {% if user.is_authenticated %}
                <a href="{%url 'myinfo' user.pk %}">
                    <div id="mypage">MyPage</div>
                </a>
                {% else %}
                <a href="{%url 'login' %}">
                    <div id="mypage">MyPage</div>
                </a>
                {% endif %}
            </div>
            <div class="nav-item">
                {% if user.is_authenticated %}
                <a href="{%url 'logout'%}">
                    <div id="logout">Log Out</div>
                </a>
                {% else %}
                <a href="{%url 'login'%}">
                    <div id="login">Log In</div>
                </a>
                {% endif %}
            </div>
        </nav>


<a id="title">My page</a>
<div id="wrap">
    <div id="section">
        <div id="var"></div>
        {% block content %}
        <form action="{% url 'update' user.pk %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <!-- 이름 -->
            <div id="name">
                <div id="namevar"><a>이름</a></div>
                <input id="nametext" type="text"  placeholder="STAR POOL" name="name">
            </div>
        <!-- 사용자 소개 -->
            <div id="intro">
                <div id="introvar"><a>사용자 소개</a></div>
                <input id="introtext" type="text"  placeholder="자신을 소개해보세요." name="bio">
            </div>
        <!-- 프로필이미지 -->
            <div id="ui">
                <div id="uivar"><a>프로필 사진</a></div>
                <div id="uisection"><img src="" class="uploadImage"></div>
                
                <div id="uiimg">
                    <input type="file" id="inputImage" value="이미지 선택" name="profile_img">
                    <button id="sendButton"><i class="fa-solid fa-camera"></i></i></button>
                </div>
            </div>

        <!-- 포트폴리오 첨부 -->
        <div id="pf">
        <div id="pfvar"><a>포트폴리오</a></div>
        <div class="filebox">
            <label for="file-input"></label>
        <input id="file-input" type="file" name="portfolio"/>
        </div>
    </div>
        <!-- 학교 입력 -->
            <div id="univ">
                <div id="univvar"><a>학교</a></div>
                <input id="univtext" type="text"  placeholder="대학교입력" name="school">
            </div> 
        <!-- 공개범위 -->
            <div id="open"><a>공개범위</a>
                <input type="checkbox" name="star" value=1> <a>별점</a>
                <input type="checkbox" name="review" value=1> <a>리뷰</a>
            </div>

            <div id="password"><a href="{%url 'change_password' user.pk %}">비밀번호 변경</a></div>
            
        <!-- 수정하기 버튼 -->
            <input type="submit" value="수정완료" id="edit"/>
        </form>
        {% endblock  %}
    </div>
</div>

<footer>
            <p class="footer">&copy; 2023 HERETHON 오디. STAR POOL ALL RIGHTS RESERVED.
            </p>
        </footer>

</body>

</html>