starpool/blogapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from blogapp import views

app_name = "blog"

urlpatterns = [
    path('', views.home, name='home'),
    path('detail/<int:id>/', views.detail, name='detail'),
    path('comment/<int:id>/', views.commentBox, name='commentBox'),
    path('detail/<int:id>/<int:comment_id>/', views.comment_detail, name='comment_detail'),

    # 이제 별점주는 채팅 어케 보내지...?
    path('commentReview/<int:id>/<int:comment_id>/', views.comment_review, name='comment_review'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

starpool/starpool/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from blogapp import views
from django.conf import settings
from django.conf.urls.static import static
from blogapp.views import initial


urlpatterns = [
    path('admin/', admin.site.urls),
    path('main/', include('blogapp.urls', namespace='blog')),
    path('accounts/',include('userapp.urls')),
    path('',initial, name="initial")

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

starpool/blogapp/models.py
from django.db import models
from userapp.models import User
#from django.core.validators import MinValueValidator, MaxValueValidator

class Post(models.Model):
    title = models.CharField(verbose_name="제목", max_length=30)
    image = models.ImageField(verbose_name="이미지", blank=True, null=True, upload_to='postImage')
    date = models.DateField(verbose_name="기간")
    
    def __str__(self) :
        return str(self.title) 
    
#평가창입력
class CommentBox(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, verbose_name="포스트", null=True)
    content = models.TextField(verbose_name="내용", max_length=500, null=False)
    # 패스워드 4자리(무조건 입력)
    comment_pw = models.CharField(verbose_name="평가코드", max_length=4, default=None, null=False)
    # auto_now_add <= 최초 작성 시간
    date = models.DateField(verbose_name="작성일", auto_now_add=True)
    writer = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="작성자",null=True)

    def __str__(self) :
        return str(self.content)

#팀원평가    
class Review(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, verbose_name="포스트", null=True)
    comment = models.ForeignKey(CommentBox, on_delete=models.CASCADE, verbose_name="댓글", null=True)
    writer = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="작성자",null=True, related_name='+')
    rating = models.IntegerField(null=True)
    review_pw = models.CharField(verbose_name="리뷰코드", max_length=4, default=None)
    review = models.TextField(verbose_name="리뷰",  max_length=100, null=False)

    def __str__(self) :
        return str(self.review)

starpool/blogapp/forms.py
from django import forms
from .models import Post

starpool/blogapp/views.py
from django.shortcuts import render
from django.shortcuts import render, redirect
from .models import Post

from userapp.models import User
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from .models import Post, CommentBox, Review
from django.http import HttpResponse
from django.http import JsonResponse
from django.contrib.auth import get_user_model


def home(request):
    posts = Post.objects.all().order_by('-id') # admin에서 생성한 공모전 post 개체 생성 
    return render(request, 'mainpage.html', {'posts':posts})

def detail(request, id):
    # pk값이 id인 Post 객체 하나를 가져와 post라는 변수에 담아줌
    post = get_object_or_404(Post, pk=id)
    comments = CommentBox.objects.filter(post=id).order_by('-id')
    context = {
        'post' : post,
        'comments': comments
    }
    return render(request, 'listpage.html', context)

# 평가해달라는 입력창
# 여기서 id가 필요힐까???
@login_required
def commentBox(request, id):
    error_message = None

    if request.method == "POST":
        post = get_object_or_404(Post, pk=id)
        comment_pw = request.POST.get('pw')
        content = request.POST.get('message')
        
        # 해당 내용들이 하나라도 없는 경우
        if not comment_pw or not content:
            error_message = '평가 코드와 내용을 입력해주세요.'
        else:
            comment = CommentBox.objects.create(
                post=post, # post필드에 해당게시물 할당
                comment_pw = comment_pw,
                content = content,
                writer = request.user #현재 로그인한 사용자
            )
            # 앱이름 안써서 한참..해맸다..
            return redirect('blog:detail', post.id)

# 평가보기 클릭시 보이는 평가디테일
# post:id, comment:id 둘다 가져옴
def comment_detail(request, id, comment_id):
    post = get_object_or_404(Post, pk=id)
    comment = get_object_or_404(CommentBox, id=comment_id)
    reviews = Review.objects.filter(comment=comment).order_by('id')

    context = {
        'post':post,
        'comment': comment,
        'reviews' :reviews,
    }
    return render(request, 'commentpage.html', context)

def comment_review(request, id, comment_id):

    if request.method == "POST":
        # url에 post:id 필요하니깐 
        post = get_object_or_404(Post, pk=id)
        comment = get_object_or_404(CommentBox, id=comment_id)
        
        rating = request.POST.get('rating')
        if rating is None or rating == '':
            rating = 0  # 또는 다른 기본값 설정
        else:
            rating = int(rating)  # 문자열을 정수로 변환

        review_pw = request.POST.get('review_pw')
        review = request.POST.get('review')

        # 평가 등록 전에 선택한 별점이 유효한지 확인
        if rating < 1 or rating > 5:
        # 별점이 유효하지 않은 경우 처리
        # 예: 오류 메시지 설정 또는 기본값으로 대체

            rating = 0

        # 비번이 같을때
        if(comment.comment_pw == review_pw):
            review = Review.objects.create(
                post=post,
                comment=comment,
                writer=request.user,
                rating=rating,
                review_pw=review_pw,
                review=review
            ) 
            # 저장
            return redirect('blog:comment_detail', id=post.id, comment_id=comment.id)
        else: #비번이 다른경우
            return HttpResponse("비밀번호가 일치하지 않습니다.")

def initial(request):
    return render(request,'splash.html')

starpool/blogapp/templates/commentpage.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>commentpage</title>
    <link rel="stylesheet" href="{% static 'css/commentpage.css' %}" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css" />
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@300;400;500;700;900&display=swap"
        rel="stylesheet" />
</head>

<body>
<nav>
            <div class="nav-item">
                <a href="{%url 'initial' %}"><img id="logo-img" src="{% static 'img/logo.png' %}" alt="navbar 로고"></img></a>
            </div>
            <div class="nav-item">
                <a href="{%url 'blog:home'%}">
                    <div id="mainpage">MainPage</div>
                </a>
                <!-- 여기 mypage, login, logout url 바꿔주세요!-->
                {% if user.is_authenticated %}
                <a href="{%url 'myinfo' user.pk %}">
                    <div id="mypage">MyPage</div>
                </a>
                {% else %}
                <a href="{%url 'login' %}">
                    <div id="mypage">MyPage</div>
                </a>
                {% endif %}
            </div>
            <div class="nav-item">
                {% if user.is_authenticated %}
                <a href="{%url 'logout'%}">
                    <div id="logout">Log Out</div>
                </a>
                {% else %}
                <a href="{%url 'login'%}">
                    <div id="login">Log In</div>
                </a>
                {% endif %}
            </div>
        </nav>

    <wrapper>
        <div class="contest-info-container">
            <a href="{% url 'blog:home' %}"><img src="{% static 'img/back-icon.png' %}" alt="뒤로가기" class="back-icon-img"
                    onclick="goToMainPage()" /></a>
            <div class="category">기획/아이디어</div>
            <div class="contest-name">{{post.title}}</div>
        </div>

        <div class="post-container">
            <div id="post">
                <!-- 게시글(흰 박스) -->
                <div id="userinfo">
                    <a href="" class="profile-img"><img src="/media/{{ comment.writer.profile_img }}" alt="프로필" /></a>
                    <div>
                        <span>{{comment.writer}}</span>
                        <div class="posttime">{{comment.date}}</div>
                    </div>
                    <div class="grade-text"><!--평균 평점--></div>
                    <div class="grade"><!--3.5---></div>
                </div>
                <hr />
                <div class="content">{{comment.content}}</div>
                <hr />

                <!-- 평가 댓글 -->
                <div class="comment-container">
                    {% for review in reviews %}
                    <div id="comment">
                        <div class="comment-top">
                            <span>{{review.writer}}</span>
                            <!-- 평가자가 준 별점 만큼 별이 채워집니다 -->
                            <div class="rating">
                                <i class="rated__star fas fa-star"></i>
                                <i class="rated__star fas fa-star"></i>
                                <i class="rated__star far fa-star"></i>
                                <i class="rated__star far fa-star"></i>
                                <i class="rated__star far fa-star"></i>
                            </div>
                        </div>
                        <!-- 평가에 입력한 내용이 뜹니다 -->
                        <div class="comment-content">{{review.review}}</div>
                    </div>
                    {% endfor %}
                </div>
                <hr />
                <!-- 평가 입력창 -->
                <div id="input-comment">
                    <form method="post" action="{% url 'blog:comment_review' id=post.id comment_id=comment.id%}">
                        {% csrf_token %}
                        <div class="comment-top">
                            <!-- 현재 로그인 유저 -->
                            <span>{{request.user.username}}</span>
                            <!--여기가 별점 매기는...-->
                            <div class="rating" name="rating">
                                <div class="rating">
                                    <i class="ratingstar far fa-star"></i>
                                    <i class="ratingstar far fa-star"></i>
                                    <i class="ratingstar far fa-star"></i>
                                    <i class="ratingstar far fa-star"></i>
                                    <i class="ratingstar far fa-star"></i>
                                    <span class="ratingresult"></span>
                                    <input type="hidden" name="rating" id="rating_input">
                                </div>
                            </div>

                            <!-- 평가 코드 입력 -->
                            <!--<img src="{%static 'img/lock.png'%}" alt="lock-image" class="lock-image" />-->
                            <div class="code-input-text">평가 코드 입력</div>
                            <input type="password" class="code-input" name="review_pw" />
                        </div>
                        <div class="comment-bottom">
                            <input type="text" placeholder="내용을 입력하세요..." class="comment-input" name="review" />
                            <!-- 평가 등록 버튼 -->
                            <button type="submit">평가 완료</button>

                        </div>
                    </form>
                </div>
                <button>목록으로 돌아가기</button>
            </div>
        </div>
    </wrapper>
    <footer>
            <p class="footer">&copy; 2023 HERETHON 오디. STAR POOL ALL RIGHTS RESERVED.
            </p>
        </footer>

    <script src="{% static 'js/commentpage.js' %}">
    </script>
</body>

</html>

starpool/blogapp/templates/listpage.html
{% load static %}
<!DOCTYPE html>

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>listpage</title>
    <link rel="stylesheet" href="{% static 'css/listpage.css' %}" />
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@300;400;500;700;900&display=swap"
        rel="stylesheet" />
</head>

<body>
        <nav>
            <div class="nav-item">
                <a href="{%url 'initial' %}"><img id="logo-img" src="{% static 'img/logo.png' %}" alt="navbar 로고"></img></a>
            </div>
            <div class="nav-item">
                <a href="{%url 'blog:home'%}">
                    <div id="mainpage">MainPage</div>
                </a>
                <!-- 여기 mypage, login, logout url 바꿔주세요!-->
                {% if user.is_authenticated %}
                <a href="{%url 'myinfo' user.pk %}">
                    <div id="mypage">MyPage</div>
                </a>
                {% else %}
                <a href="{%url 'login' %}">
                    <div id="mypage">MyPage</div>
                </a>
                {% endif %}
            </div>
            <div class="nav-item">
                {% if user.is_authenticated %}
                <a href="{%url 'logout'%}">
                    <div id="logout">Log Out</div>
                </a>
                {% else %}
                <a href="{%url 'login'%}">
                    <div id="login">Log In</div>
                </a>
                {% endif %}
            </div>
        </nav>

    <wrapper>
        <!-- 공모전 카테고리 및 이름 -->
        <div class="contest-info-container">
            <img src="{% static 'img/back-icon.png' %}" alt="뒤로가기" class="back-icon-img" onclick="goToMainPage()" />
            <div class="category">기획/아이디어</div>
            <!--해당 공모전 제목가져오기-->
            <div class="contest-name">{{ post.title}}</div>
        </div>

        <div class="post-container" style="overflow-x: scroll;">
            <!-- 게시글 등록창 -->
            <form method="post" action="{% url 'blog:commentBox' post.id%}">
                {% csrf_token %}

                <div id="input-post">
                    <div id="userinfo">
                        <img src="/media/{{ request.user.profile_img }}" alt="프로필" class="profile-img" />
                        <div>
                            <span>{{ request.user.name }}</span>
                        </div>
                        <!-- 평가 코드 -->
                        <div class="code-input-text">평가 코드 설정</div>
                        <input type="password" class="code-input" id="pw" name="pw" />
                    </div>
                    <!-- 게시글 내용 입력 -->
                    <input type="text" placeholder="내용을 입력하세요..." class="content-input" id="message" name="message" />

                    {% if error_message %}
                    <div class="error-message">{{ error_message }}</div>
                    {% endif %}

                    <hr />
                    <!-- 게시글 등록 버튼 -->
                    <button type="submit">등록</button>


                </div>
            </form>

            <!-- 여기서 왜 댓글을 관리자 페이지에서 포스트위치를 지정해 줘야만 나오는가...?-->
            {% for comment in comments %}
            <div id="post">
                <div id="userinfo">
                    <a href="userpage.html" class="profile-img"><img src="/media/{{ comment.writer.profile_img }}" alt="프로필" /></a>
                    <div>
                        <span>{{comment.writer}}</span>
                        <div class="posttime">{{ comment.date }}</div>
                    </div>
                    <div class="grade-text"><!--평균 평점--></div>
                    <!-- 평가자가 남긴 평점의 평균이 숫자로 띄워집니다 -->
                    <div class="grade"><!--평가가 있을시 --></div>
                </div>
                <hr />
                <!-- 게시글에 입력한 내용이 뜹니다 -->
                <div class="content">{{ comment.content }}</div>
                <button><a href="{% url 'blog:comment_detail' comment.post.id comment.id %}">평가하기</a></button>
                <hr />
            </div>
            {% endfor %}
        </div>
    </wrapper>

    <footer>
            <p class="footer">&copy; 2023 HERETHON 오디. STAR POOL ALL RIGHTS RESERVED.
            </p>
        </footer>

    <script>
        // 뒤로가기 버튼 클릭시 메인페이지
        function goToMainPage() {
            location.href = "{% url 'blog:home' %}";
        }
    </script>
</body>

</html>

starpool/blogapp/templates/mainpage.html
{% load static %}
<!DOCTYPE html>

<head>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"
        integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <title></title>
    <link rel="stylesheet" href="{% static 'css/mainpage.css' %}" />
</head>

<body>
    <div class="content">
        <nav>
            <div class="nav-item">
                <a href="{%url 'initial' %}"><img id="logo-img" src="{% static 'img/logo.png' %}" alt="navbar 로고"></img></a>
            </div>
            <div class="nav-item">
                <a href="{%url 'blog:home'%}">
                    <div id="mainpage">MainPage</div>
                </a>
                <!-- 여기 mypage, login, logout url 바꿔주세요!-->
                {% if user.is_authenticated %}
                <a href="{%url 'myinfo' user.pk %}">
                    <div id="mypage">MyPage</div>
                </a>
                {% else %}
                <a href="{%url 'login' %}">
                    <div id="mypage">MyPage</div>
                </a>
                {% endif %}
            </div>
            <div class="nav-item">
                {% if user.is_authenticated %}
                <a href="{%url 'logout'%}">
                    <div id="logout">Log Out</div>
                </a>
                {% else %}
                <a href="{%url 'login'%}">
                    <div id="login">Log In</div>
                </a>
                {% endif %}
            </div>
        </nav>

        <div id="wrap">
            <div id="aside">
                <div class="search">
                    <input type="text" id="search" placeholder="   공모전 검색">
                    <img id="img-search" src="https://s3.ap-northeast-2.amazonaws.com/cdn.wecode.co.kr/icon/search.png">
                </div>
                <div id="s1" class="button" onclick="buttonClick('s1')"><a>기획/아이디어</a></div>
                <div id="s2" class="button" onclick="buttonClick('s2')"><a>영상/UCC/사진</a></div>
                <div id="s3" class="button" onclick="buttonClick('s3')"><a>광고/마케팅</a></div>
                <div id="s4" class="button" onclick="buttonClick('s4')"><a>디자인/캐릭터/웹툰</a></div>
                <div id="s5" class="button" onclick="buttonClick('s5')"><a>웹/모바일/플래시</a></div>
                <div id="s6" class="button" onclick="buttonClick('s6')"><a>논문/리포트</a></div>
                <div id="s7" class="button" onclick="buttonClick('s7')"><a>네이밍/슬로건</a></div>
                <div id="s8" class="button" onclick="buttonClick('s8')"><a>게임/소프트웨어</a></div>
            </div>

            <div id="grid-container" class="scrollbar" style="overflow-x:hidden; height:600px; width:1100px;">
                {% for post in posts %}
                {% include 'post.html'%}
                {% endfor %}
            </div>
        </div>
    </div>



    <footer>
        <p class="footer">&copy; 2023 HERETHON 오디. STAR POOL ALL RIGHTS RESERVED.
        </p>
    </footer>

    <script src="mainpage.js"></script>
</body>

</html>

starpool/blogapp/templates/post.html
{% load static %}
<!DOCTYPE html>

<head>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"
        integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <title></title>
    <link href="{% static 'css/mainpage.css' %}" rel="stylesheet" />
</head>

<body>
    <div id="gridgrid">
        <!-- 이미지 사이즈 안됨-->
        <div class="grid-item {% cycle 'item1' 'item2' %}">
            <!--이미지 출력-->
            <!--div 클래스에 맞춤으로 사진 나오게 하는 방법 -->
            {% if post.image %}
            <img class="item1" src="{{ post.image.url}}" width="330" height="200">
            {% endif %}
        </div>
        <div id="gridsection">
            <a id="kind">기획/아이디어</a>
            <div id="title">
                <a href="{% url 'blog:detail' post.id %}">{{post.title}}</a>
            </div>
            <a id="num"><i class="fa-solid fa-align-left"></i>4</a>
            <a id="day"><i class="fa-regular fa-calendar-minus"></i> {{post.date}}</a>
        </div>
    </div>
</body>

</html>

starpool/blogapp/templates/splash.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Star Pool</title>
        <link rel="stylesheet" href="{% static 'css/splash.css' %}" />
        <!-- <link href="{% static 'css/splash.css' %}" rel="stylesheet" /> -->
    </head>
    <body>
        <div class="content">
        <nav>
            <div class="nav-item">
                <a href="{%url 'initial' %}"><img id="logo-img" src="{% static 'img/logo.png' %}" alt="navbar 로고"></img></a>
            </div>
            <div class="nav-item">
                <a href="{%url 'blog:home'%}">
                    <div id="mainpage">MainPage</div>
                </a>
                <!-- 여기 mypage, login, logout url 바꿔주세요!-->
                {% if user.is_authenticated %}
                <a href="{%url 'myinfo' user.pk %}">
                    <div id="mypage">MyPage</div>
                </a>
                {% else %}
                <a href="{%url 'login' %}">
                    <div id="mypage">MyPage</div>
                </a>
                {% endif %}
            </div>
            <div class="nav-item">
                {% if user.is_authenticated %}
                <a href="{%url 'logout'%}">
                    <div id="logout">Log Out</div>
                </a>
                {% else %}
                <a href="{%url 'login'%}">
                    <div id="login">Log In</div>
                </a>
                {% endif %}
            </div>
        </nav>

            <div id="start">
                <img id="logo-main" src="./images/logo_3.png" alt="로고 이미지3" >
                <p class="info">
                    'STAR POOL'은<br />
                    사용자의 포트폴리오와 팀원 상호간의 평가 시스템을 기반으로
                    공모전 참가자들이 자신과 잘 맞는 팀원을 찾을 기회를 제공하는
                    플랫폼입니다.
                </p>
                <a href="./signup.html"
                    ><div id="start-app">Start STAR POOL</div></a
                >
            </div>
            <div id="func">
                <div class="item">
                    <img src="./images/icon_01.png" alt="포트폴리오 조회">
                    <h3 class="func-title">포트폴리오 조회</h3>
                    <div class="container">
                        <p class="func-info">
                            사용자는 STAR POOL에 회원가입 후 <br />
                            개인정보와 포트폴리오를 등록할 수 있으며,<br />
                            다른 사용자의 포트폴리오를 조회할 수 있습니다.
                        </p>
                    </div>
                </div>
                <div class="item">
                    <img src="./images/icon_02.png" alt="팀 프로젝트 평가">
                    <h3 class="func-title">팀 프로젝트 평가</h3>
                    <div class="container">
                        <p class="func-info">
                            공모전에 같이 참여한 팀원들은 <br />
                            서로의 태도, 적극성, 기술적인 역량 등을<br />
                            평가할 수 있습니다.
                        </p>
                    </div>
                </div>
                <div class="item">
                    <img src="./images/icon_03.png" alt="공모전 정보 제공">
                    <h3 class="func-title">공모전 정보 제공</h3>
                    <div class="container">
                        <p class="func-info">
                            STAR POOL은 다양한 공모전 정보를 제공합니다.
                        </p>
                    </div>
                </div>
            </div>
        </div>

        <footer>
            <p class="footer">&copy; 2023 HERETHON 오디. STAR POOL ALL RIGHTS RESERVED.
            </p>
        </footer>
    </body>
</html>